[package]
name = "cidacake-client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.26"
solana-sdk = "1.18.26"
solana-program = "1.18.26"
borsh = "0.10.3"
spl-token = "4.0.0"
clap = { version = "4.0", features = ["derive"] }